import Head from "next/head";
import StepVerify from "../components/step-verify";

export default function Verify() {
  return (
    <div>
      <Head>
        <title>Form Verify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className="d-flex w-100 flex-column justify-content-start align-items-center pt-5"
          style={{ height: "100vh" }}
        >
          <StepVerify />
        </div>
      </main>
    </div>
  );
}
